M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 August 17, Wednesday 11:35:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-17T11:35:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T2
X48.5Y-52.0
T1
X31.201Y-25.5G85X30.201Y-25.5
G05
X31.201Y-78.5G85X30.201Y-78.5
G05
T0
M30
