M48
; DRILL file {KiCad (6.0.5-0)} date 2022 June 06, Monday 23:04:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-06T23:04:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T2
X48.5Y-52.0
T1
X31.201Y-25.5G85X30.201Y-25.5
G05
X31.201Y-78.5G85X30.201Y-78.5
G05
T0
M30
